## Part 1: Preprocessing

In [10]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [11]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [12]:
# Create y_df with the Attrition and Department columns

y_df = attrition_df[['Attrition', 'Department']]
y_df.head()

Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [18]:
# Create a list of at least 10 column names to use as X data

selected_columns = [
    'Age', 'BusinessTravel', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction',
    'HourlyRate', 'JobLevel', 'JobSatisfaction', 'JobRole', 'MaritalStatus'
]



# Create X_df using your selected columns
X_df = attrition_df[selected_columns]
print(X_df.head())
# Show the data types for X_df
X_df.dtypes
print(X_df.dtypes)


   Age     BusinessTravel  DistanceFromHome  Education  \
0   41      Travel_Rarely                 1          2   
1   49  Travel_Frequently                 8          1   
2   37      Travel_Rarely                 2          2   
3   33  Travel_Frequently                 3          4   
4   27      Travel_Rarely                 2          1   

   EnvironmentSatisfaction  HourlyRate  JobLevel  JobSatisfaction  \
0                        2          94         2                4   
1                        3          61         2                2   
2                        4          92         1                3   
3                        4          56         1                3   
4                        1          40         1                2   

                 JobRole MaritalStatus  
0        Sales Executive        Single  
1     Research Scientist       Married  
2  Laboratory Technician        Single  
3     Research Scientist       Married  
4  Laboratory Technician       

In [19]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)


In [45]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
for column in ['BusinessTravel', 'JobRole', 'MaritalStatus']:
    X_train[column] = label_encoder.fit_transform(X_train[column])
    X_test[column] = label_encoder.transform(X_test[column])
# Verify the changes
X_train.head()
X_test.head()

Age  BusinessTravel  DistanceFromHome  Education  \
1041   28               2                 5          3   
184    53               2                13          2   
1222   24               2                22          1   
67     45               2                 7          3   
220    36               2                 5          2   

      EnvironmentSatisfaction  HourlyRate  JobLevel  JobSatisfaction  JobRole  \
1041                        4          84         2                1        7   
184                         4          57         2                1        4   
1222                        4          58         1                3        1   
67                          2          59         3                1        6   
220                         4          62         2                2        2   

      MaritalStatus  
1041              2  
184               0  
1222              1  
67                0  
220               2

In [21]:
# Create a StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled[:5])
print(X_test_scaled[:5])


[[-1.38855944  0.58928051  1.44039645 -0.86335572  0.2797056  -0.47283217
  -0.9322736  -1.58233648 -1.00880128 -1.48641297]
 [-2.04073779 -2.46355596 -0.52269928 -0.86335572 -0.63910385  0.30937375
  -0.9322736   1.15283407  0.609133    1.27071897]
 [-0.84507748  0.58928051  1.31770296 -0.86335572  1.19851504 -1.05948661
  -0.02544667  1.15283407  1.01361657 -1.48641297]
 [ 0.24188644  0.58928051  0.3361551   0.09993302  1.19851504 -0.03284134
  -0.02544667 -0.67061296 -0.19983414 -0.107847  ]
 [-0.62768469  0.58928051  1.31770296  0.09993302 -0.63910385  1.09157967
  -0.02544667  0.24111056 -1.00880128 -1.48641297]]
[[-0.95377387  0.58928051 -0.52269928  0.09993302  1.19851504  0.84714032
  -0.02544667 -1.58233648  1.01361657  1.27071897]
 [ 1.76363593  0.58928051  0.45884859 -0.86335572  1.19851504 -0.47283217
  -0.02544667 -1.58233648 -0.19983414 -1.48641297]
 [-1.38855944  0.58928051  1.56308993 -1.82664446  1.19851504 -0.4239443
  -0.9322736   0.24111056 -1.41328485 -0.107847  ]


In [22]:
# Create a OneHotEncoder for the Department column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_dept = OneHotEncoder(sparse=False)
# Fit the encoder to the training data
onehot_encoder_dept.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_dept_encoded = onehot_encoder_dept.transform(y_train[['Department']])
y_test_dept_encoded = onehot_encoder_dept.transform(y_test[['Department']])
print(y_train_dept_encoded[:5])
print(y_test_dept_encoded[:5])



[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [23]:
# Create a OneHotEncoder for the Attrition column
onehot_encoder_attr = OneHotEncoder(sparse=False)

# Fit the encoder to the training data
onehot_encoder_attr.fit(y_train[['Attrition']])


# Create two new variables by applying the encoder
# to the training and testing data
y_train_attr_encoded = onehot_encoder_attr.transform(y_train[['Attrition']])
y_test_attr_encoded = onehot_encoder_attr.transform(y_test[['Attrition']])
print(y_train_attr_encoded[:5])
print(y_test_attr_encoded[:5])


[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


## Create, Compile, and Train the Model

In [37]:
# Find the number of columns in the X training data
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
input_dim = X_train_scaled.shape[1]
print(f"Number of columns in X training data: {input_dim}")

# Create the input layer

input_layer = Input(shape=(input_dim,))
# Create at least two shared layers
shared_layer_1 = Dense(64, activation='relu', name='shared1')(input_layer)
shared_layer_2 = Dense(128, activation='relu', name='shared2')(shared_layer_1)

Number of columns in X training data: 10


In [38]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer
dept_branch_hidden = Dense(32, activation='relu', name='department_hidden')(shared_layer_2)
dept_output = Dense(3, activation='softmax', name='department_output')(dept_branch_hidden)


In [39]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer
attr_branch_hidden = Dense(32, activation='relu', name='attrition_hidden')(shared_layer_2)
attr_output = Dense(2, activation='softmax', name='attrition_output')(attr_branch_hidden)

In [40]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output, attr_output])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Summarize the model
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_3 (InputLayer)        [(None, 10)]                 0         []                            
                                                                                                  
 shared1 (Dense)             (None, 64)                   704       ['input_3[0][0]']             
                                                                                                  
 shared2 (Dense)             (None, 128)                  8320      ['shared1[0][0]']             
                                                                                                  
 department_hidden (Dense)   (None, 32)                   4128      ['shared2[0][0]']             
                                                                                            

In [41]:
# Train the model

history = model.fit(
    X_train_scaled,
    {'department_output': y_train_dept_encoded, 'attrition_output': y_train_attr_encoded},
    epochs=50,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/50
30/30 [==============================] - 2s 15ms/step - loss: 1.4242 - department_output_loss: 0.9334 - attrition_output_loss: 0.4908 - department_output_accuracy: 0.5330 - attrition_output_accuracy: 0.8287 - val_loss: 1.2650 - val_department_output_loss: 0.7394 - val_attrition_output_loss: 0.5257 - val_department_output_accuracy: 0.6314 - val_attrition_output_accuracy: 0.7966
Epoch 2/50
30/30 [==============================] - 0s 4ms/step - loss: 1.0969 - department_output_loss: 0.6708 - attrition_output_loss: 0.4261 - department_output_accuracy: 0.7234 - attrition_output_accuracy: 0.8404 - val_loss: 1.0744 - val_department_output_loss: 0.5958 - val_attrition_output_loss: 0.4785 - val_department_output_accuracy: 0.8093 - val_attrition_output_accuracy: 0.7966
Epoch 3/50
30/30 [==============================] - 0s 4ms/step - loss: 0.9465 - department_output_loss: 0.5360 - attrition_output_loss: 0.4106 - department_output_accuracy: 0.8436 - attrition_output_accuracy: 0.8404 - 

In [42]:
# Evaluate the model with the testing data
results = model.evaluate(X_test_scaled,
                         {'department_output': y_test_dept_encoded, 'attrition_output': y_test_attr_encoded})

# Print the evaluation results

10/10 [==============================] - 0s 6ms/step - loss: 1.1955 - department_output_loss: 0.4647 - attrition_output_loss: 0.7308 - department_output_accuracy: 0.8844 - attrition_output_accuracy: 0.8163


In [43]:
# Print the accuracy for both department and attrition
print(f"Total loss: {results[0]}")
print(f"Department loss: {results[1]}")
print(f"Attrition loss: {results[2]}")
print(f"Department prediction accuracy: {results[3]}")
print(f"Attrition prediction accuracy: {results[4]}")

Total loss: 1.1954658031463623
Department loss: 0.46468058228492737
Attrition loss: 0.7307852506637573
Department prediction accuracy: 0.884353756904602
Attrition prediction accuracy: 0.8163265585899353


# Summary


1. Is accuracy the best metric to use on this data? Why or why not?
Accuracy is a useful metric, but it might not be the best metric to use for this data. The dataset could be imbalanced with more instances of one class than the other, particularly for the attrition prediction (i.e., more employees might not leave than those who do). In such cases, accuracy can be misleading because a model could achieve high accuracy by simply predicting the majority class. Other metrics like precision, recall, F1-score, and AUC-ROC can provide a more comprehensive understanding of model performance, especially for the minority class.We chose the softmax activation function for both output layers:

2. What activation functions did you choose for your output layers, and why?Department output layer: Dense(3, activation='softmax')
This layer is designed for multi-class classification to predict one of three possible departments.
Attrition output layer: Dense(2, activation='softmax')
This layer is used for binary classification to predict whether an employee will leave or stay.
The softmax activation function converts logits into probabilities, making it suitable for multi-class and binary classification problems by ensuring that the output probabilities sum to one.
3. Can you name a few ways that this model might be improved?
Feature Engineering,Hyperparameter Tuning,Regularization,Cross-Validation,Handling Class Imbalance,Advanced Architectures,Combining predictions from multiple models to reduce variance and improve generalization.